### ISSUE TITLE
RuntimeWarning: divide by zero encountered in log

### ISSUE THREAD

**Issue by jmrichardson** [fracdiff/fracdiff#101]
Hi, thank you for this great library.  I am hoping you can help with this warning:

```
D:\Anaconda3\envs\aim\lib\site-packages\statsmodels\regression\linear_model.py:926: RuntimeWarning: divide by zero encountered in log
  llf = -nobs2*np.log(2*np.pi) - nobs2*np.log(ssr / nobs) - nobs2
```

Are these warning something to be concerned about?  Thanks for any insight

**Comment by ghost** [comment]
Thanks for your inquiry.
That warning happens when, for instance, one applies FracdiffStat to an array filled with zero or a constant: https://github.com/fracdiff/fracdiff/issues/4

**Comment by ghost** [comment]
That is due to `adfuller` stationarity test in statsmodels. Reproduction here:

```py
from statsmodels.tsa.stattools import adfuller
import numpy as np

x = np.ones(100).reshape(-1, 1)
result = adfuller(x)

print(result)
```

```txt
/opt/homebrew/lib/python3.9/site-packages/statsmodels/regression/linear_model.py:926: RuntimeWarning: divide by zero encountered in log
  llf = -nobs2*np.log(2*np.pi) - nobs2*np.log(ssr / nobs) - nobs2
(nan, nan, 0, 99, {'1%': -3.498198082189098, '5%': -2.891208211860468, '10%': -2.5825959973472097}, -inf)
```

This may be something to be concerned about as a transformed time series will be nan.
Anyways this is a problem (possibly a bug) of statsmodels and unfortunately, there's nothing fracdiff can do for it.
Maybe you could tell statsmodels team to handle this problem.

**Comment by jmrichardson** [comment]
Awesome!  Yes, that was the problem.  Thank you for the fast reply!  :)
