### ISSUE TITLE
Inverse FracDiff

### ISSUE THREAD

**Issue by khalidsalomao** [fracdiff/fracdiff#41]
Hi @simaki , thanks for the great project!

I am wondering if it is possible to inverse the fractional differentiation transformation so it can be used for instance on a SKLearn regressions pipeline or similar forecasting pipelines, in order to revert the forecasted value to the original scale.

Thanks!

**Comment by ghost** [comment]
The inverse of `d`-th fracdiff is `-d`-th fracdiff because `(1-D)^(-d) (1-D)^d = 1` where `D` denotes a lag operator. A caveat is, while this relation is mathematically true, in practical computation fracdiff truncates the Taylor expansion of `(1-D)^d` and so it is approximate.

This library would run for a negative `d` but the validity of the output has not been tested (I hope right though).

Thank you so much for your interest, @khalidsalomao !

**Comment by khalidsalomao** [comment]
@simaki thanks for your kind response!

Sure the truncation may affect precision depending on the problem data, but I would guess that in most cases of forecasting or regression a small additional error can be tolerated if the fracdiff improves the problem modeling (this indeed needs to be tested).

Could you write a small example of the inverse transformation?

I was unsure of how to use the fracdiff coefficients to transform a sequence of forecasted values back to the original scale.

Thanks!

**Comment by ghost** [comment]
Yes, fdiff and Fracdiff run for negative d:

```py
x = ...  # 1d array

y = fdiff(x, -0.5)
y = Fracdiff(-0.5).fit_transform(x.reshape(-1, 1))
```

**Comment by khalidsalomao** [comment]
@simaki 
Thanks a lot for the example!

I tested with some time series but unfortunately the difference were significative on those series: 
![image](https://user-images.githubusercontent.com/1336766/124396095-07ffff00-dcde-11eb-8c38-231c7229a196.png)

Thanks!

**Comment by ghost** [comment]
Thank you for sharing that! Closing.

**Comment by ghost** [comment]
Related: -d does not return back the original series https://github.com/fracdiff/fracdiff/issues/127
