### ISSUE TITLE
Upper limit above 1?

### ISSUE THREAD

**Issue by jmrichardson** [fracdiff/fracdiff#92]
Hi,

I have certain dataframes which produce Nans for d_.   However, if I change the upper parameter from 1 to lets say 2, it fixes the problem and some d_ are higher than 1.  Is this correct?  I thought 1 would be the highest to make stationary or are there cases where greater than 1 is needed?  Thanks for any insight.

**Comment by ghost** [comment]
I presume that is expected behavior.

For time series with [order of integration](https://en.wikipedia.org/wiki/Order_of_integration) that is greater than 1, d_, the differentiation needed to make it stationary, would be greater than 1.

Examples of time series with, say, d_ = 2, include the cumulative sum of a Brownian motion. If one differentiates it only once the time series is a Brownian motion. To make it stationary one has to apply differentiations twice to get white noise.

**Comment by ghost** [comment]
If you have anything still unclear please do not hesitate to reopen this. Thank you for using this, @jmrichardson !

**Comment by jmrichardson** [comment]
Awesome!  Thank you for the fast response!
